<?xml version="1.0" encoding="utf-8"?><Database Name="BasisForAppraisalDB" Class="BFADataBasedbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LENOVO-PC-YAIR;Initial Catalog=BasisForAppraisalDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BasisForAppraisalDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblForm" Member="tblForms">
    <Type Name="tblForm">
      <Column Name="FormId" Member="formId" Storage="_FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="tblForm_tbl_IntentionalQuestion" Member="tbl_IntentionalQuestions" ThisKey="formId" OtherKey="FormId" Type="tbl_IntentionalQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_IntentionalQuestion" Member="tbl_IntentionalQuestions">
    <Type Name="tbl_IntentionalQuestion">
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="tbl_IntentionalQuestion_tbl_IntentionalAnswer" Member="tbl_IntentionalAnswers" ThisKey="FormId,QuestionId" OtherKey="FormId,QuestionId" Type="tbl_IntentionalAnswer" />
      <Association Name="tblForm_tbl_IntentionalQuestion" Member="tblForm" ThisKey="FormId" OtherKey="formId" Type="tblForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_IntentionalAnswer" Member="tbl_IntentionalAnswers">
    <Type Name="tbl_IntentionalAnswer">
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AnswerOption" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_IntentionalQuestion_tbl_IntentionalAnswer" Member="tbl_IntentionalQuestion" ThisKey="FormId,QuestionId" OtherKey="FormId,QuestionId" Type="tbl_IntentionalQuestion" IsForeignKey="true" />
    </Type>
  </Table>
</Database>