<?xml version="1.0" encoding="utf-8"?><Database Name="BasisForAppraisalAWS" Class="BFADataBasedbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=basisfor.cba825xpbtm6.us-west-2.rds.amazonaws.com,1433;Initial Catalog=BasisForAppraisalAWS;Persist Security Info=True;User ID=BFE;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BasisForAppraisalAWSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Section" Member="tbl_Sections">
    <Type Name="tbl_Section">
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HelpExplanation" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="tbl_Section_tbl_IntentionalQuestion" Member="tbl_IntentionalQuestions" ThisKey="FormId,SectionId" OtherKey="FormId,SectionId" Type="tbl_IntentionalQuestion" />
      <Association Name="tblForm_tbl_Section" Member="tblForm" ThisKey="FormId" OtherKey="formId" Type="tblForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Company" Member="tbl_Companies">
    <Type Name="tbl_Company">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="comapnyName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="comapnyAddress" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="comapnyPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Company_tbl_Unit" Member="tbl_Units" ThisKey="companyId" OtherKey="companyId" Type="tbl_Unit" />
      <Association Name="tbl_Company_tbl_ConnectorFormFill" Member="tbl_ConnectorFormFills" ThisKey="companyId" OtherKey="companyId" Type="tbl_ConnectorFormFill" />
      <Association Name="tbl_Company_ReportForOrganiztion" Member="ReportForOrganiztions" ThisKey="companyId" OtherKey="CompanyId" Type="ReportForOrganiztion" />
      <Association Name="tbl_Company_ReportForIndividual" Member="ReportForIndividuals" ThisKey="companyId" OtherKey="CompanyId" Type="ReportForIndividual" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Class" Member="tbl_Classes">
    <Type Name="tbl_Class">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="unitName" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="className" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_Class_tbl_Employee" Member="tbl_Employees" ThisKey="companyId,unitName,className" OtherKey="companyId,unitName,className" Type="tbl_Employee" />
      <Association Name="tbl_Unit_tbl_Class" Member="tbl_Unit" ThisKey="companyId,unitName" OtherKey="companyId,unitName" Type="tbl_Unit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Unit" Member="tbl_Units">
    <Type Name="tbl_Unit">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="unitName" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_Unit_tbl_Class" Member="tbl_Classes" ThisKey="companyId,unitName" OtherKey="companyId,unitName" Type="tbl_Class" />
      <Association Name="tbl_Company_tbl_Unit" Member="tbl_Company" ThisKey="companyId" OtherKey="companyId" Type="tbl_Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_IntentionalAnswer" Member="tbl_IntentionalAnswers">
    <Type Name="tbl_IntentionalAnswer">
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="AnswerOption" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_IntentionalAnswer_tbl_ConnectorAnswer" Member="tbl_ConnectorAnswers" ThisKey="FormId,SectionId,QuestionId,AnswerId" OtherKey="FormId,SectionId,QuestionId,AnswerId" Type="tbl_ConnectorAnswer" />
      <Association Name="tbl_IntentionalQuestion_tbl_IntentionalAnswer" Member="tbl_IntentionalQuestion" ThisKey="FormId,SectionId,QuestionId" OtherKey="FormId,SectionId,QuestionId" Type="tbl_IntentionalQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ConnectorFormFill" Member="tbl_ConnectorFormFills">
    <Type Name="tbl_ConnectorFormFill">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employeeFillId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employeeOnId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="formId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="done" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tbl_ConnectorFormFill_tbl_ConnectorAnswer" Member="tbl_ConnectorAnswers" ThisKey="companyId,employeeFillId,employeeOnId,formId" OtherKey="companyId,employeeFillId,employeeOnId,formConnectorId" Type="tbl_ConnectorAnswer" />
      <Association Name="tbl_Company_tbl_ConnectorFormFill" Member="tbl_Company" ThisKey="companyId" OtherKey="companyId" Type="tbl_Company" IsForeignKey="true" />
      <Association Name="tbl_Employee_tbl_ConnectorFormFill" Member="tbl_Employee" ThisKey="employeeFillId" OtherKey="employeeId" Type="tbl_Employee" IsForeignKey="true" />
      <Association Name="tbl_Employee_tbl_ConnectorFormFill1" Member="tbl_Employee1" ThisKey="employeeOnId" OtherKey="employeeId" Type="tbl_Employee" IsForeignKey="true" />
      <Association Name="tblForm_tbl_ConnectorFormFill" Member="tblForm" ThisKey="formId" OtherKey="formId" Type="tblForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ConnectorAnswers" Member="tbl_ConnectorAnswers">
    <Type Name="tbl_ConnectorAnswer">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employeeFillId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employeeOnId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="formConnectorId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="tbl_ConnectorFormFill_tbl_ConnectorAnswer" Member="tbl_ConnectorFormFill" ThisKey="companyId,employeeFillId,employeeOnId,formConnectorId" OtherKey="companyId,employeeFillId,employeeOnId,formId" Type="tbl_ConnectorFormFill" IsForeignKey="true" />
      <Association Name="tbl_IntentionalAnswer_tbl_ConnectorAnswer" Member="tbl_IntentionalAnswer" ThisKey="FormId,SectionId,QuestionId,AnswerId" OtherKey="FormId,SectionId,QuestionId,AnswerId" Type="tbl_IntentionalAnswer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Employee" Member="tbl_Employees">
    <Type Name="tbl_Employee">
      <Column Name="companyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unitName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="className" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="employeeId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IsManger" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsAccompanied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbl_Employee_tbl_ConnectorFormFill" Member="tbl_ConnectorFormFills" ThisKey="employeeId" OtherKey="employeeFillId" Type="tbl_ConnectorFormFill" />
      <Association Name="tbl_Employee_tbl_ConnectorFormFill1" Member="tbl_ConnectorFormFills1" ThisKey="employeeId" OtherKey="employeeOnId" Type="tbl_ConnectorFormFill" />
      <Association Name="tbl_Employee_ReportForIndividual" Member="ReportForIndividuals" ThisKey="employeeId" OtherKey="IndividualId" Type="ReportForIndividual" />
      <Association Name="tbl_Class_tbl_Employee" Member="tbl_Class" ThisKey="companyId,unitName,className" OtherKey="companyId,unitName,className" Type="tbl_Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportForIndividualLines" Member="ReportForIndividualLines">
    <Type Name="ReportForIndividualLine">
      <Column Name="IndividualId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FromId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestioFormId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SelfEvaluation" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="collegesEvaluation" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SupervisorEvaluation" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AccompaniedEvaluation" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CountOfFormsFilled" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalAverage" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="tbl_IntentionalQuestion_ReportForIndividualLine" Member="tbl_IntentionalQuestion" ThisKey="QuestioFormId,SectionId,QuestionId" OtherKey="FormId,SectionId,QuestionId" Type="tbl_IntentionalQuestion" IsForeignKey="true" />
      <Association Name="ReportForIndividual_ReportForIndividualLine" Member="ReportForIndividual" ThisKey="IndividualId,FromId" OtherKey="IndividualId,FormId" Type="ReportForIndividual" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblForm" Member="tblForms">
    <Type Name="tblForm">
      <Column Name="formId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FormName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lastChange" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="introduction" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tblForm_tbl_Section" Member="tbl_Sections" ThisKey="formId" OtherKey="FormId" Type="tbl_Section" />
      <Association Name="tblForm_tbl_ConnectorFormFill" Member="tbl_ConnectorFormFills" ThisKey="formId" OtherKey="formId" Type="tbl_ConnectorFormFill" />
      <Association Name="tblForm_ReportForOrganiztion" Member="ReportForOrganiztions" ThisKey="formId" OtherKey="FormId" Type="ReportForOrganiztion" />
      <Association Name="tblForm_ReportForIndividual" Member="ReportForIndividuals" ThisKey="formId" OtherKey="FormId" Type="ReportForIndividual" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_IntentionalQuestion" Member="tbl_IntentionalQuestions">
    <Type Name="tbl_IntentionalQuestion">
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="HelpText" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="QuestionType" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="MandatoryQuestion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfAnswers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ForManager" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ForAccompanied" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ForSelf" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Forcolleagues" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ForReports" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tbl_IntentionalQuestion_tbl_IntentionalAnswer" Member="tbl_IntentionalAnswers" ThisKey="FormId,SectionId,QuestionId" OtherKey="FormId,SectionId,QuestionId" Type="tbl_IntentionalAnswer" />
      <Association Name="tbl_IntentionalQuestion_ReportForIndividualLine" Member="ReportForIndividualLines" ThisKey="FormId,SectionId,QuestionId" OtherKey="QuestioFormId,SectionId,QuestionId" Type="ReportForIndividualLine" />
      <Association Name="tbl_IntentionalQuestion_ReportForOrganiztionLine" Member="ReportForOrganiztionLines" ThisKey="FormId,SectionId,QuestionId" OtherKey="QuestioFormId,SectionId,QuestionId" Type="ReportForOrganiztionLine" />
      <Association Name="tbl_Section_tbl_IntentionalQuestion" Member="tbl_Section" ThisKey="FormId,SectionId" OtherKey="FormId,SectionId" Type="tbl_Section" IsForeignKey="true" />
      <Association Name="tbl_TypeQuestion_tbl_IntentionalQuestion" Member="tbl_TypeQuestion" ThisKey="QuestionType" OtherKey="Name" Type="tbl_TypeQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportForOrganiztion" Member="ReportForOrganiztions">
    <Type Name="ReportForOrganiztion">
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LastCalculationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Isclose" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ReportForOrganiztion_ReportForOrganiztionLine" Member="ReportForOrganiztionLines" ThisKey="CompanyId,FormId" OtherKey="CompanyId,FormId" Type="ReportForOrganiztionLine" />
      <Association Name="tbl_Company_ReportForOrganiztion" Member="tbl_Company" ThisKey="CompanyId" OtherKey="companyId" Type="tbl_Company" IsForeignKey="true" />
      <Association Name="tblForm_ReportForOrganiztion" Member="tblForm" ThisKey="FormId" OtherKey="formId" Type="tblForm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportForIndividual" Member="ReportForIndividuals">
    <Type Name="ReportForIndividual">
      <Column Name="IndividualId" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="feedback" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsClose" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ReportForIndividual_ReportForIndividualLine" Member="ReportForIndividualLines" ThisKey="IndividualId,FormId" OtherKey="IndividualId,FromId" Type="ReportForIndividualLine" />
      <Association Name="tbl_Company_ReportForIndividual" Member="tbl_Company" ThisKey="CompanyId" OtherKey="companyId" Type="tbl_Company" IsForeignKey="true" />
      <Association Name="tblForm_ReportForIndividual" Member="tblForm" ThisKey="FormId" OtherKey="formId" Type="tblForm" IsForeignKey="true" />
      <Association Name="tbl_Employee_ReportForIndividual" Member="tbl_Employee" ThisKey="IndividualId" OtherKey="employeeId" Type="tbl_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReportForOrganiztionLines" Member="ReportForOrganiztionLines">
    <Type Name="ReportForOrganiztionLine">
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestioFormId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HighScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LowScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeQuestionName" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="MidScore" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ReportForOrganiztion_ReportForOrganiztionLine" Member="ReportForOrganiztion" ThisKey="CompanyId,FormId" OtherKey="CompanyId,FormId" Type="ReportForOrganiztion" IsForeignKey="true" />
      <Association Name="tbl_IntentionalQuestion_ReportForOrganiztionLine" Member="tbl_IntentionalQuestion" ThisKey="QuestioFormId,SectionId,QuestionId" OtherKey="FormId,SectionId,QuestionId" Type="tbl_IntentionalQuestion" IsForeignKey="true" />
      <Association Name="tbl_TypeQuestion_ReportForOrganiztionLine" Member="tbl_TypeQuestion" ThisKey="TypeQuestionName" OtherKey="Name" Type="tbl_TypeQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TypeQuestion" Member="tbl_TypeQuestions">
    <Type Name="tbl_TypeQuestion">
      <Column Name="Name" Type="System.String" DbType="VarChar(300) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tbl_TypeQuestion_tbl_IntentionalQuestion" Member="tbl_IntentionalQuestions" ThisKey="Name" OtherKey="QuestionType" Type="tbl_IntentionalQuestion" />
      <Association Name="tbl_TypeQuestion_ReportForOrganiztionLine" Member="ReportForOrganiztionLines" ThisKey="Name" OtherKey="TypeQuestionName" Type="ReportForOrganiztionLine" />
    </Type>
  </Table>
</Database>